#spring:
#  config:
#    import: "optional:configserver:http://config-service:8088"
#    activate:
#      on-profile: docker
#---
spring:
  application:
    name: department-service
  config:
#    import: "optional:configserver:http://localhost:8088"
    import: "optional:configserver:http://192.168.198.128:8088"
management.tracing.enabled: false
management.tracing.sampling.probability: 0.0