spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8088"
  main:
    web-application-type: reactive
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web: DEBUG